package export

import (
	"bytes"
	"fmt"
	"sort"
	"strings"

	"github.com/jung-kurt/gofpdf"
)

// severity palette (RGB) for the PDF, matching the web UI.
var pdfSevColor = map[string][3]int{
	"critical": {229, 72, 77},
	"high":     {239, 114, 52},
	"medium":   {216, 160, 30},
	"low":      {76, 130, 247},
	"info":     {139, 141, 152},
}

// PDF renders a branded report. logoPNG may be nil (header falls back to text).
func PDF(sc Scan, logoPNG []byte) []byte {
	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.SetTitle("Obscura Scan Report", false)
	pdf.SetAutoPageBreak(true, 18)
	pdf.SetMargins(18, 16, 18)

	risk, level := scanRiskLevel(sc.Results)
	findings := ExtractFindings(sc.Results)

	pdf.AddPage()

	// ---- header band ----
	pdf.SetFillColor(13, 14, 17)
	pdf.Rect(0, 0, 210, 34, "F")
	if len(logoPNG) > 0 {
		pdf.RegisterImageOptionsReader("logo", gofpdf.ImageOptions{ImageType: "PNG"}, bytes.NewReader(logoPNG))
		pdf.ImageOptions("logo", 18, 8, 18, 18, false, gofpdf.ImageOptions{ImageType: "PNG"}, 0, "")
	}
	pdf.SetTextColor(244, 244, 245)
	pdf.SetXY(40, 10)
	pdf.SetFont("Helvetica", "B", 18)
	pdf.CellFormat(0, 8, "Obscura Scan", "", 1, "L", false, 0, "")
	pdf.SetX(40)
	pdf.SetFont("Helvetica", "", 9)
	pdf.SetTextColor(161, 161, 170)
	pdf.CellFormat(0, 5, "Threat Hunter & Attack Surface Report", "", 1, "L", false, 0, "")
	pdf.Ln(14)

	// ---- target meta ----
	pdf.SetTextColor(20, 20, 25)
	pdf.SetFont("Helvetica", "B", 15)
	pdf.CellFormat(0, 9, tr(sc.Target), "", 1, "L", false, 0, "")
	pdf.SetFont("Helvetica", "", 9)
	pdf.SetTextColor(110, 110, 120)
	pdf.CellFormat(0, 6, tr(fmt.Sprintf("Scan #%d  ·  %s", sc.ID, sc.ScanDate.Format("2006-01-02 15:04 MST"))), "", 1, "L", false, 0, "")
	pdf.Ln(4)

	// ---- risk summary box ----
	col := pdfSevColor[level]
	pdf.SetDrawColor(225, 225, 230)
	pdf.SetFillColor(250, 250, 251)
	y := pdf.GetY()
	pdf.RoundedRect(18, y, 174, 26, 2, "1234", "DF")
	pdf.SetXY(24, y+5)
	pdf.SetTextColor(col[0], col[1], col[2])
	pdf.SetFont("Helvetica", "B", 26)
	pdf.CellFormat(34, 16, fmt.Sprintf("%d", risk), "", 0, "L", false, 0, "")
	pdf.SetXY(60, y+6)
	pdf.SetFont("Helvetica", "B", 11)
	pdf.CellFormat(0, 6, "Risk Score "+strings.Title(level), "", 1, "L", false, 0, "")
	pdf.SetX(60)
	pdf.SetFont("Helvetica", "", 9)
	pdf.SetTextColor(110, 110, 120)
	counts := countBy(findings)
	pdf.CellFormat(0, 6, tr(fmt.Sprintf("Critical %d   High %d   Medium %d   Low %d   ·   %d findings",
		counts["critical"], counts["high"], counts["medium"], counts["low"], len(findings))), "", 1, "L", false, 0, "")
	pdf.SetY(y + 32)

	// ---- findings ----
	pdf.SetTextColor(20, 20, 25)
	pdf.SetFont("Helvetica", "B", 12)
	pdf.CellFormat(0, 8, "Findings", "", 1, "L", false, 0, "")
	if len(findings) == 0 {
		pdf.SetFont("Helvetica", "I", 9)
		pdf.SetTextColor(120, 120, 130)
		pdf.CellFormat(0, 6, "No findings of note for the modules run.", "", 1, "L", false, 0, "")
	}
	rank := map[string]int{"critical": 0, "high": 1, "medium": 2, "low": 3, "info": 4}
	sort.SliceStable(findings, func(i, j int) bool { return rank[findings[i].Severity] < rank[findings[j].Severity] })
	for _, f := range findings {
		c := pdfSevColor[f.Severity]
		if c == [3]int{} {
			c = pdfSevColor["info"]
		}
		yy := pdf.GetY()
		pdf.SetFillColor(c[0], c[1], c[2])
		pdf.Rect(18, yy+1, 2, 7, "F")
		pdf.SetX(23)
		pdf.SetTextColor(c[0], c[1], c[2])
		pdf.SetFont("Helvetica", "B", 8)
		pdf.CellFormat(20, 6, strings.ToUpper(f.Severity), "", 0, "L", false, 0, "")
		pdf.SetTextColor(30, 30, 38)
		pdf.SetFont("Helvetica", "", 9)
		pdf.CellFormat(110, 6, tr(f.Title), "", 0, "L", false, 0, "")
		pdf.SetTextColor(140, 140, 150)
		pdf.SetFont("Helvetica", "", 8)
		pdf.CellFormat(0, 6, tr(f.Module), "", 1, "R", false, 0, "")
	}
	pdf.Ln(4)

	// ---- module coverage ----
	if meta, ok := sc.Results["_meta"].(map[string]any); ok {
		if ms, ok := meta["module_status"].(map[string]any); ok && len(ms) > 0 {
			pdf.SetTextColor(20, 20, 25)
			pdf.SetFont("Helvetica", "B", 12)
			pdf.CellFormat(0, 8, "Module Coverage", "", 1, "L", false, 0, "")
			names := make([]string, 0, len(ms))
			for k := range ms {
				names = append(names, k)
			}
			sort.Strings(names)
			pdf.SetFont("Helvetica", "", 9)
			for _, n := range names {
				st, _ := ms[n].(string)
				switch st {
				case "success":
					pdf.SetTextColor(48, 164, 108)
				case "error":
					pdf.SetTextColor(229, 72, 77)
				default:
					pdf.SetTextColor(216, 160, 30)
				}
				pdf.CellFormat(40, 5, "  "+st, "", 0, "L", false, 0, "")
				pdf.SetTextColor(60, 60, 68)
				pdf.CellFormat(0, 5, tr(n), "", 1, "L", false, 0, "")
			}
		}
	}

	// ---- footer ----
	pdf.SetFooterFunc(func() {
		pdf.SetY(-12)
		pdf.SetFont("Helvetica", "", 7)
		pdf.SetTextColor(160, 160, 170)
		pdf.CellFormat(0, 6, tr(fmt.Sprintf("Generated by Obscura Scan · Security-Life.org · page %d", pdf.PageNo())), "", 0, "C", false, 0, "")
	})

	var buf bytes.Buffer
	if err := pdf.Output(&buf); err != nil {
		return []byte("PDF generation error: " + err.Error())
	}
	return buf.Bytes()
}

func countBy(fs []Finding) map[string]int {
	m := map[string]int{}
	for _, f := range fs {
		m[f.Severity]++
	}
	return m
}

func scanRiskLevel(results map[string]any) (int, string) {
	if sum, ok := results["_summary"].(map[string]any); ok {
		score := 0
		switch v := sum["risk_score"].(type) {
		case float64:
			score = int(v)
		case int:
			score = v
		}
		level, _ := sum["risk_level"].(string)
		if level == "" {
			level = "info"
		}
		return score, level
	}
	return 0, "info"
}

// tr makes a string safe for gofpdf's core fonts, which expect single-byte
// cp1252/latin-1 — so we emit the rune's byte value (not its UTF-8 encoding)
// for code points < 256, and substitute everything else.
func tr(s string) string {
	var b strings.Builder
	for _, r := range s {
		switch {
		case r == '·':
			b.WriteByte(0xB7) // middle dot in cp1252
		case r == '—' || r == '–':
			b.WriteByte('-')
		case r < 256:
			b.WriteByte(byte(r))
		default:
			b.WriteByte('?')
		}
	}
	return b.String()
}
